export { default as Authors } from './Authors.vue'
export { default as Avatar } from './Avatar.vue'
export { default as GitChangelog } from './GitChangelog.vue'
export { default as GitContributors } from './GitContributors.vue'
export { default as GitInfo } from './GitInfo.vue'
