name: CR

on:
  push:
  pull_request:
    branches: [main]
    paths-ignore:
      - '.github/**'
      - 'tests/**'
      - 'docs/**'
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: pnpm

      - name: Install
        run: pnpm i

      - name: Build
        run: pnpm build

      - run: pnpx pkg-pr-new publish
